backend/models/DynamicModel.php
<?php
 
namespace backend\models;
 
use Yii;
 
class DynamicModel extends \yii\base\DynamicModel
{    
    public function getIsNewRecord()
    { 
        return true;
    }
}

backend/controllers/ProposalController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Proposal;
use backend\models\ProposalSearch;
use backend\models\ProposalFile;
use backend\models\ProposalFileSearch;
use backend\models\ProposalLuaran;
use backend\models\ProposalLuaranSearch;
use backend\models\Anggota;
use backend\models\AnggotaSearch;
use backend\models\LaporanKemajuan;
use backend\models\LaporanKemajuanSearch;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\IntegrityException;

/**
 * ProposalController implements the CRUD actions for Proposal model.
 */
class ProposalController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Proposal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProposalSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Proposal model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $queryParams = Yii::$app->request->queryParams;

        $searchModel = new LaporanKemajuanSearch();
        if (!isset($queryParams['LaporanKemajuanSearch'])) $queryParams['LaporanKemajuanSearch'] = [];
        $queryParams['LaporanKemajuanSearch'] = array_merge($queryParams['LaporanKemajuanSearch'], ['proposal_id' => $id]);
        $dataProvider = $searchModel->search($queryParams);
        $dataProvider->pagination = false;

        $searchModelFile = new ProposalFileSearch();
        if (!isset($queryParams['ProposalFileSearch'])) $queryParams['ProposalFileSearch'] = [];
        $queryParams['ProposalFileSearch'] = array_merge($queryParams['ProposalFileSearch'], ['proposal_id' => $id]);
        $dataProviderFile = $searchModelFile->search($queryParams);
        $dataProviderFile->pagination = false;

        $searchModelLuaran = new ProposalLuaranSearch();
        if (!isset($queryParams['ProposalLuaranSearch'])) $queryParams['ProposalLuaranSearch'] = [];
        $queryParams['ProposalLuaranSearch'] = array_merge($queryParams['ProposalLuaranSearch'], ['proposal_id' => $id]);
        $dataProviderLuaran = $searchModelLuaran->search($queryParams);
        $dataProviderLuaran->pagination = false;

        $searchModelAnggota = new AnggotaSearch();
        if (!isset($queryParams['AnggotaSearch'])) $queryParams['AnggotaSearch'] = [];
        $queryParams['AnggotaSearch'] = array_merge($queryParams['AnggotaSearch'], ['proposal_id' => $id]);
        $dataProviderAnggota = $searchModelAnggota->search($queryParams);
        $dataProviderAnggota->pagination = false;

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'searchModelFile' => $searchModelFile,
            'dataProviderFile' => $dataProviderFile,
            'searchModelLuaran' => $searchModelLuaran,
            'dataProviderLuaran' => $dataProviderLuaran,
            'searchModelAnggota' => $searchModelAnggota,
            'dataProviderAnggota' => $dataProviderAnggota,
        ]);
    }

    /**
     * Creates a new Proposal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Proposal();
        $model->dosen_user_id = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // print '<pre>'; print_r($model); die();
            foreach ($model->luarans as $luaran) {
                $modelPL = new ProposalLuaran();
                $modelPL->proposal_id = $model->id;
                $modelPL->luaran_id = $luaran;
                $modelPL->save();
            }
            if (($uploadedFile = UploadedFile::getInstance($model, 'file_proposal')) !== null) {
                $modelFile = new ProposalFile();
                $modelFile->proposal_id = $model->id;
                $modelFile->tanggal_upload = date('Y-m-d H:i:s');
                if ($modelFile->save()) {
                    $filename = 'proposalfile' . $modelFile->id . '.' . $uploadedFile->extension;
                    $uploadedFile->saveAs(Yii::getAlias('@uploads/' . $filename));
                    $modelFile->file_proposal = $filename;
                    $modelFile->save();
                }
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Proposal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            /* if (($uploadedFile = UploadedFile::getInstance($model, 'file_proposal')) !== null) {
                $filename = 'proposal' . $model->id . '.' . $uploadedFile->extension;
                $uploadedFile->saveAs(Yii::getAlias('@uploads/' . $filename));
                $model->file_proposal = $filename;
                $model->save();
            } */
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDisposisi($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('disposisi', [
                'model' => $model,
            ]);
        }
    }

    public function actionReview($id)
    {
        $model = $this->findModel($id);
        $model->tanggal_review = date('Y-m-d H:i:s');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (($uploadedFile = UploadedFile::getInstance($model, 'file_review')) !== null) {
                $filename = 'review' . $model->id . '.' . $uploadedFile->extension;
                $uploadedFile->saveAs(Yii::getAlias('@uploads/' . $filename));
                $model->file_review = $filename;
                $model->save();
            }
            if (($uploadedFile = UploadedFile::getInstance($model, 'file_penilaian')) !== null) {
                $filename = 'penilaian' . $model->id . '.' . $uploadedFile->extension;
                $uploadedFile->saveAs(Yii::getAlias('@uploads/' . $filename));
                $model->file_penilaian = $filename;
                $model->save();
            }
            return $this->redirect(['index']);
        } else {
            return $this->render('review', [
                'model' => $model,
            ]);
        }
    }


    public function actionAnggota($id)
    {
        $model = $this->findModel($id);
        $modelLK = new Anggota();
        $modelLK->proposal_id = $model->id;

        if ($modelLK->load(Yii::$app->request->post()) && $modelLK->save()) {
            return $this->redirect(['anggota', 'id' => $modelLK->proposal_id]);
        }

        $searchModel = new AnggotaSearch();
        $queryParams = Yii::$app->request->queryParams;
        if (!isset($queryParams['AnggotaSearch'])) $queryParams['AnggotaSearch'] = [];
        $queryParams['AnggotaSearch'] = array_merge($queryParams['AnggotaSearch'], ['proposal_id' => $model->id]);
        $dataProvider = $searchModel->search($queryParams);
        $dataProvider->pagination = false;

        return $this->render('anggota', [
            'model' => $model,
            'modelLK' => $modelLK,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionAnggotaDelete($id)
    {
        try {
            $modelLK = Anggota::findOne($id);
            $modelLK->delete();
            return $this->redirect(['anggota', 'id' => $modelLK->proposal_id]);
        } catch (IntegrityException $e) {
            throw new \yii\web\HttpException(500, "Integrity Constraint Violation. This data can not be deleted due to the relation.", 405);
        }
    }


    public function actionProposalFile($id)
    {
        $model = $this->findModel($id);
        $modelLK = new ProposalFile();
        $modelLK->proposal_id = $model->id;
        $modelLK->tanggal_upload = date('Y-m-d H:i:s');

        if ($modelLK->load(Yii::$app->request->post()) && $modelLK->save()) {
            if (($uploadedFile = UploadedFile::getInstance($modelLK, 'file_proposal')) !== null) {
                $filename = 'proposalfile' . $modelLK->id . '.' . $uploadedFile->extension;
                $uploadedFile->saveAs(Yii::getAlias('@uploads/' . $filename));
                $modelLK->file_proposal = $filename;
                $modelLK->save();
                return $this->redirect(['proposal-file', 'id' => $modelLK->proposal_id]);
            }
        }

        $searchModel = new ProposalFileSearch();
        $queryParams = Yii::$app->request->queryParams;
        if (!isset($queryParams['ProposalFileSearch'])) $queryParams['ProposalFileSearch'] = [];
        $queryParams['ProposalFileSearch'] = array_merge($queryParams['ProposalFileSearch'], ['proposal_id' => $model->id]);
        $dataProvider = $searchModel->search($queryParams);

backend/views/proposal/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\datecontrol\DateControl;
use kartik\widgets\FileInput;
use backend\models\User;
use backend\models\JenisKegiatan;
use backend\models\SumberDana;
use backend\models\Luaran;

/* @var $this yii\web\View */
/* @var $model backend\models\Proposal */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="proposal-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'judul')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'ringkasan')->textarea(['rows' => 2]) ?>

    <?php /*echo $form->field($model, 'dosen_user_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(User::find()->all(), 'id', 'username'),
        'options' => ['placeholder' => ''],
        'pluginOptions' => ['allowClear' => true],
    ]);*/ ?>

    <?= $form->field($model, 'jenis_kegiatan_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(JenisKegiatan::find()->all(), 'id', 'nama'),
        'options' => ['placeholder' => ''],
        'pluginOptions' => ['allowClear' => true],
    ]); ?>

    <?= $form->field($model, 'tanggal_pengajuan')->widget(DateControl::classname(), [
        // 'type' => DatePicker::TYPE_COMPONENT_PREPEND,
        'readonly' => true,
        'pluginOptions' => ['autoclose' => true,/*  'format' => 'yyyy-mm-dd' */],
    ]); ?>

    <?= $form->field($model, 'total_biaya')->textInput() ?>

    <?= $form->field($model, 'sumber_dana_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(SumberDana::find()->all(), 'id', 'nama'),
        'options' => ['placeholder' => ''],
        'pluginOptions' => ['allowClear' => true],
    ]); ?>

    <?= $form->field($model, 'luarans')->checkBoxList(ArrayHelper::map(Luaran::find()->all(), 'id', 'nama'))->label('Luaran') ?>

    <?= $form->field($model, 'file_proposal')->widget(FileInput::classname(), [
        'options' => [
            'accept' => 'application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'pluginOptions' => [
            'showPreview' => false,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false,
            'allowedFileExtensions' => ['pdf', 'PDF', 'docx', 'DOCX', 'doc', 'DOC'],
				// 'maxFileSize' => 8192,
        ]
    ]); ?>
    
    <div class="form-panel">
        <div class="row">
    	    <div class="col-sm-6 col-sm-offset-3">
    	        <?= Html::submitButton('<i class="glyphicon glyphicon-ok"></i> ' . ($model->isNewRecord ? 'Create' : 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
	    </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/proposal/anggota.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\widgets\FileInput;
use backend\models\User;
use backend\models\JenisKegiatan;
use backend\models\SumberDana;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model backend\models\Proposal */

$this->title = 'Anggota';
$this->params['breadcrumbs'][] = ['label' => 'Proposals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->judul, 'url' => ['view', 'id' => $model->id]];
?>
<div class="proposal-create box box-success">
	<!-- <div class="box-header"></div> -->

    <div class="box-body">

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
							// 'id',
                'kode',
				'judul',
				'ringkasan:ntext',
				'dosenUser.username:text:Dosen',
				'jenisKegiatan.nama:text:Jenis Kegiatan',
				'tanggal_pengajuan',
				'total_biaya:integer',
				'sumberDana.nama:text:Sumber Dana',
			],
		]) ?>
		<br>

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
				'tanggal_disposisi',
				'reviewerUser.username:text:Reviewer',
				'tanggal_review:date',
				[
					'attribute' => 'hasil_review',
					'value' => $model->hasil_review ? $model->hasilReviews($model->hasil_review) : '',
				],
				'keterangan_review:ntext',
				[
					'attribute' => 'file_review',
					'format' => 'raw',
					'value' => Html::a($model->file_review, ['download', 'filename' => $model->file_review]),
				],
			],
		]) ?>
		<br>
		<br>

		<div class="proposal-form">

		    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'options' => ['enctype' => 'multipart/form-data']]); ?>

			<?= $form->field($modelLK, 'nama_anggota')->textInput(); ?>
			
			<div class="form-panel">
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3">
						<?= Html::submitButton('<i class="glyphicon glyphicon-ok"></i> ' . ($modelLK->isNewRecord ? 'Create' : 'Update'), ['class' => $modelLK->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
					</div>
				</div>
			</div>

			<?php ActiveForm::end(); ?>

		</div>
		
		<div style="padding-top:20px">

		<?php 
	$gridColumns = [
		[
			'class' => 'yii\grid\SerialColumn',
			'headerOptions' => ['class' => 'text-right serial-column'],
			'contentOptions' => ['class' => 'text-right serial-column'],
		],
		[
			'contentOptions' => ['class' => 'action-column nowrap text-left'],
			'class' => 'yii\grid\ActionColumn',
			'template' => '{anggota-delete}',
			'buttons' => [
				'view' => function ($url) {
					return '';
				},
				'update' => function ($url) {
					return Html::a('', $url, ['class' => 'glyphicon glyphicon-pencil btn btn-xs btn-default btn-text-warning']);
				},
				'anggota-delete' => function ($url) {
					return Html::a('', $url, [
						'class' => 'glyphicon glyphicon-trash btn btn-xs btn-default btn-text-danger',
						'data-method' => 'post',
						'data-confirm' => 'Are you sure you want to delete this item?'
					]);
				},
			],
		],
		'nama_anggota',		
	];
	?>

        <?= GridView::widget([
								'dataProvider' => $dataProvider,
            // 'pjax' => true,
								'hover' => true,
								'striped' => false,
								'bordered' => false,
								'toolbar' => [
									Html::a('<i class="fa fa-plus"></i> ' . 'Create', ['create'], ['class' => 'btn btn-success']),
									Html::a('<i class="fa fa-repeat"></i> ' . 'Reload', ['index'], ['data-pjax' => 0, 'class' => 'btn btn-default']),
									'{toggleData}',
								],
								'panel' => false,
								'pjaxSettings' => ['options' => ['id' => 'grid']],
            // 'filterModel' => $searchModel,
								'columns' => $gridColumns,
							]); ?>

		</div>

    </div>

</div>

backend/views/proposal/disposisi.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\datecontrol\DateControl;
use backend\models\User;
use backend\models\JenisKegiatan;
use backend\models\SumberDana;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Proposal */

$this->title = 'Disposisi';
$this->params['breadcrumbs'][] = ['label' => 'Proposals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->judul, 'url' => ['view', 'id' => $model->id]];
// $this->params['breadcrumbs'][] = $this->title;

if (!$model->tanggal_disposisi) $model->tanggal_disposisi = date('Y-m-d');
?>

<div class="proposal-create box box-success">
	<!-- <div class="box-header"></div> -->

    <div class="box-body">

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
							// 'id',
                'kode',
				'judul',
				'ringkasan:ntext',
				'dosenUser.longText:text:Dosen',
				'jenisKegiatan.nama:text:Jenis Kegiatan',
				'tanggal_pengajuan',
				'total_biaya:integer',
				'sumberDana.nama:text:Sumber Dana',
			],
		]) ?>
		<br>
		<br>

		<div class="proposal-form">

			<?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

			<?= $form->field($model, 'tanggal_disposisi')->widget(DateControl::classname(), [
						// 'type' => DatePicker::TYPE_COMPONENT_PREPEND,
						'readonly' => true,
						'pluginOptions' => ['autoclose' => true, /* 'format' => 'yyyy-mm-dd' */],
					]); ?>

			<?= $form->field($model, 'reviewer_user_id')->widget(Select2::classname(), [
						'data' => ArrayHelper::map(User::find()->joinWith(['roles'])->where(['item_name' => 'reviewer'])->all(), 'id', 'longText'),
						'options' => ['placeholder' => ''],
						'pluginOptions' => ['allowClear' => true],
					]); ?>

			
			<div class="form-panel">
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3">
						<?= Html::submitButton('<i class="glyphicon glyphicon-ok"></i> ' . ($model->isNewRecord ? 'Create' : 'Disposisi'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
					</div>
				</div>
			</div>

			<?php ActiveForm::end(); ?>

		</div>

    </div>

</div>

backend/views/proposal/laporan-akhir.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\datecontrol\DateControl;
use kartik\widgets\FileInput;
use backend\models\User;
use backend\models\JenisKegiatan;
use backend\models\SumberDana;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Proposal */

$this->title = 'Laporan Akhir';
$this->params['breadcrumbs'][] = ['label' => 'Proposals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->judul, 'url' => ['view', 'id' => $model->id]];
?>
<div class="proposal-create box box-success">
	<!-- <div class="box-header"></div> -->

    <div class="box-body">

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
				// 'id',
                'kode',
				'judul',
				'ringkasan:ntext',
				'dosenUser.longText:text:Dosen',
				'jenisKegiatan.nama:text:Jenis Kegiatan',
				'tanggal_pengajuan:date',
				'total_biaya:integer',
				'sumberDana.nama:text:Sumber Dana',
			],
		]) ?>
		<br>

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
				'tanggal_disposisi:date',
				'reviewerUser.longText:text:Reviewer',
				'tanggal_review:date',
				[
					'attribute' => 'hasil_review',
					'value' => $model->hasil_review ? $model->hasilReviews($model->hasil_review) : '',
				],
				'keterangan_review:ntext',
				[
					'attribute' => 'file_review',
					'format' => 'raw',
					'value' => Html::a($model->file_review, ['download', 'filename' => $model->file_review]),
				],
			],
		]) ?>
		<br>
		<br>

		<div class="proposal-form">

		    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'options' => ['enctype' => 'multipart/form-data']]); ?>

			<?= $form->field($model, 'tanggal_laporan_akhir')->widget(DateControl::classname(), [
						// 'type' => DatePicker::TYPE_COMPONENT_PREPEND,
						'readonly' => true,
						'pluginOptions' => ['autoclose' => true, 'format' => 'yyyy-mm-dd'],
					]); ?>

			<?= $form->field($model, 'file_laporan_akhir')->widget(FileInput::className(), [
				'options' => [
					'accept' => 'application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document',
				],
				'pluginOptions' => [
					'showPreview' => false,
					'showCaption' => true,
					'showRemove' => true,
					'showUpload' => false,
					'allowedFileExtensions' => ['pdf', 'PDF', 'docx', 'DOCX', 'doc', 'DOC'],
					// 'maxFileSize' => 8192,
				]
			]) ?>
			
			<div class="form-panel">
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3">
						<?= Html::submitButton('<i class="glyphicon glyphicon-ok"></i> ' . ($model->isNewRecord ? 'Create' : 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
					</div>
				</div>
			</div>

			<?php ActiveForm::end(); ?>

		</div>

    </div>

</div>

backend/views/proposal/review.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\datecontrol\DateControl;
use kartik\widgets\FileInput;
use backend\models\User;
use backend\models\JenisKegiatan;
use backend\models\SumberDana;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Proposal */

$this->title = 'Review';
$this->params['breadcrumbs'][] = ['label' => 'Proposals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->judul, 'url' => ['view', 'id' => $model->id]];
// $this->params['breadcrumbs'][] = $this->title;
?>

<div class="proposal-create box box-success">
	<!-- <div class="box-header"></div> -->

    <div class="box-body">

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
						// 'id',
                'kode',
				'judul',
				'ringkasan:ntext',
				'dosenUser.longText:text:Dosen',
				'jenisKegiatan.nama:text:Jenis Kegiatan',
				'tanggal_pengajuan:date',
				'total_biaya:integer',
				'sumberDana.nama:text:Sumber Dana',
			],
		]) ?>
		<br>

		<?= DetailView::widget([
			'options' => ['class' => 'table detail-view'],
			'model' => $model,
			'attributes' => [
				'tanggal_disposisi:date',
				'reviewerUser.longText:text:Reviewer',
			],
		]) ?>
		<br>
		<br>
		
		<div class="proposal-form">

		    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'options' => ['enctype' => 'multipart/form-data']]); ?>

			<?= $form->field($model, 'tanggal_review')->widget(DatePicker::classname(), [
						'type' => DatePicker::TYPE_COMPONENT_PREPEND,
						'readonly' => true,
						// 'type' => DateControl::FORMAT_DATETIME,
						// 'autoWidget' => false,
						'pluginOptions' => ['autoclose' => true, 'format' => 'yyyy-mm-dd'],
					]); ?>

			<?= $form->field($model, 'hasil_review')->dropDownList($model->hasilReviews(), ['prompt' => '']) ?>

			<?= $form->field($model, 'file_review')->widget(FileInput::classname(), [
			'options' => [
				'accept' => 'application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			],
			'pluginOptions' => [
				'showPreview' => false,
				'showCaption' => true,
				'showRemove' => true,
				'showUpload' => false,
				'allowedFileExtensions' => ['pdf', 'PDF', 'docx', 'DOCX', 'doc', 'DOC'],
				// 'maxFileSize' => 8192,
			]
		]); ?>

		<?= $form->field($model, 'file_penilaian')->widget(FileInput::classname(), [
		'options' => [
			'accept' => 'application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		],
		'pluginOptions' => [
			'showPreview' => false,
			'showCaption' => true,
			'showRemove' => true,
			'showUpload' => false,
			'allowedFileExtensions' => ['pdf', 'PDF', 'docx', 'DOCX', 'doc', 'DOC'],
				// 'maxFileSize' => 8192,
		]
		]); ?>

			<?= $form->field($model, 'keterangan_review')->textarea(['rows' => 6]) ?>

			
			<div class="form-panel">
				<div class="row">
					<div class="col-sm-6 col-sm-offset-3">
						<?= Html::submitButton('<i class="glyphicon glyphicon-ok"></i> ' . ($model->isNewRecord ? 'Create' : 'Review'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
					</div>
				</div>
			</div>

			<?php ActiveForm::end(); ?>

		</div>

    </div>

</div>